version: '3.3'
services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi:latest
    restart: unless-stopped
    ports:
      - "1337:1337"

